excluded:
  - DamBudgetUITests/SnapshotHelper.swift

disabled_rules: # rule identifiers to exclude from running
  - todo
opt_in_rules: # some rules are only opt-in
  - attributes
  - array_init
  # - async_without_await # not released yet
  - balanced_xctest_lifecycle
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - direct_return
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - file_name
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  # - no_empty_block # not released yet
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_swiftui_state
  - prohibited_super_call
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_self_in_closure
  - redundant_type_annotation
  - required_enum_case
  - return_value_from_void_function
  - shorthand_optional_binding
  - sorted_first_last
  - sorted_imports
  - static_operator
  - superfluous_else
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unhandled_throwing_task
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  # - unused_parameter # not released yet
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

analyzer_rules:
  - capture_variable
  - unused_declaration
  - unused_import

attributes:
  always_on_same_line: ["@Environment", "@AppStorage", "@Query", "@UIApplicationDelegateAdaptor"]

closure_body_length:
  warning: 50
  error: 100

empty_count:
  only_after_dot: true

file_types_order:
  order: [[main_type], [supporting_type], [extension], [preview_provider], [library_content_provider]]

identifier_name:
  min_length:
    warning: 2
    error: 2

number_separator:
  minimum_length: 5

type_name:
  max_length:
    warning: 50
    error: 60
